[package]
name = "gitback"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
git2 = "0.20.2"
octocrab = "0.47.0"
tokio = { version = "1.47.1", features = ["full"] }
futures = "0.3.31"
tempfile = "3.23.0"
chrono = "0.4.42"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
